/**
 * Serving uploaded photos.
 *
 * Uploads are served through this route rather than as static files, on purpose.
 * The upload directory sits outside anything the static handler can reach, so
 * nothing in it is ever interpreter-mapped or reachable by guessing a path, and
 * the content type sent to the browser comes from our own validation at upload
 * time rather than from anything the client supplied or that is stored alongside
 * the file.
 *
 * The random public id is obscurity, not access control. Authorization is
 * enforced here before a single byte is read.
 */

import fs from 'node:fs';
import path from 'node:path';
import { requireAuth } from '../auth/middleware.js';
import { getPhotoForServing } from '../db/surveys.js';
import { sanitizeDisplayFilename } from '../lib/photos.js';

/**
 * Content types we are willing to emit. The stored value is checked against this
 * allowlist rather than trusted, so a tampered database row cannot make us send
 * `text/html` for a file a browser would then execute on our own origin.
 */
const SERVABLE_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);

/**
 * @param {import('hono').Hono} app
 */
export function registerPhotoRoutes(app) {
  app.get('/photos/:publicId', requireAuth(), (c) => {
    const config = c.get('config');
    const user = c.get('user');

    const photo = getPhotoForServing(c.req.param('publicId'));
    if (!photo) return c.notFound();

    // Same rule as the survey itself: someone else's photo is reported missing
    // rather than forbidden, so a probe cannot confirm the id exists.
    if (user.role !== 'admin' && photo.owner_id !== user.id) {
      return c.notFound();
    }

    if (!SERVABLE_TYPES.has(photo.mime_type)) {
      return c.notFound();
    }

    // The stored name was generated by us (a UUID plus a canonical extension),
    // but resolve and confirm containment anyway so a tampered row can never
    // reach outside the upload directory.
    const fullPath = path.join(config.uploadDir, photo.storage_name);
    const uploadRoot = path.resolve(config.uploadDir) + path.sep;
    if (!path.resolve(fullPath).startsWith(uploadRoot)) {
      return c.notFound();
    }

    let stat;
    try {
      stat = fs.statSync(fullPath);
      if (!stat.isFile()) return c.notFound();
    } catch {
      // The row exists but the file is gone. Report missing rather than 500:
      // there is nothing the viewer can do about it.
      return c.notFound();
    }

    const etag = `"${photo.storage_name}-${stat.size}"`;
    if (c.req.header('if-none-match') === etag) {
      return c.body(null, 304, { ETag: etag });
    }

    const body = fs.readFileSync(fullPath);
    const displayName = sanitizeDisplayFilename(photo.original_name ?? 'photo');

    return c.body(body, 200, {
      // Our validated type, never the claimed one.
      'Content-Type': photo.mime_type,
      // Without nosniff a browser could sniff an image-typed file as HTML and
      // run it on our origin. The global header sets this too; repeated here
      // because it matters most on exactly this route.
      'X-Content-Type-Options': 'nosniff',
      // Inline so it can render in the page, with a sanitized filename for the
      // save dialog.
      'Content-Disposition': `inline; filename="${displayName}"`,
      ETag: etag,
      // Private: these are one user's photos, so no shared cache should keep them.
      'Cache-Control': 'private, max-age=3600, must-revalidate',
    });
  });
}
