/**
 * Uploads that have been accepted but are not attached to a survey yet.
 *
 * See 002_pending_photos.sql for why this exists. In short: a browser cannot
 * repopulate a file input, so a survey that fails validation would otherwise
 * lose a photo the server had already accepted and written to disk.
 *
 * Every function here treats the token as an identifier, never as authorization.
 * Ownership is checked against the requesting user on redemption, so guessing a
 * token (already infeasible at 32 random bytes) still would not attach someone
 * else's photo to your survey.
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { db } from './index.js';
import { nowIso } from '../lib/format.js';

/**
 * How long an accepted-but-unattached upload survives.
 *
 * Long enough to correct a typo, make a phone call, and come back. Short enough
 * that an abandoned draft does not keep megabytes on disk indefinitely.
 */
const TTL_MS = 6 * 60 * 60 * 1000;

/** @param {number} ms */
function isoIn(ms) {
  return new Date(Date.now() + ms).toISOString().replace(/\.\d{3}Z$/, 'Z');
}

/**
 * Record an accepted upload against a user, returning the token to echo in the
 * form.
 *
 * @param {{userId: number, stored: object}} input `stored` is a storePhoto result
 * @returns {string} the token
 */
export function createPendingPhoto({ userId, stored }) {
  const token = crypto.randomBytes(32).toString('base64url');
  const meta = stored.metadata ?? {};

  db()
    .prepare(
      `INSERT INTO pending_photos
         (token, user_id, storage_name, mime_type, byte_size, sha256, original_name,
          gps_latitude, gps_longitude, gps_altitude_m, had_gps,
          captured_at, captured_at_raw, camera_make, camera_model,
          created_at, expires_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    )
    .run(
      token,
      userId,
      stored.storageName,
      stored.mimeType,
      stored.byteSize,
      stored.sha256,
      stored.originalName ?? null,
      Number.isFinite(meta.gpsLatitude) ? meta.gpsLatitude : null,
      Number.isFinite(meta.gpsLongitude) ? meta.gpsLongitude : null,
      Number.isFinite(meta.gpsAltitudeMetres) ? meta.gpsAltitudeMetres : null,
      meta.hadGps ? 1 : 0,
      meta.capturedAt ?? null,
      meta.capturedAtRaw ?? null,
      meta.cameraMake ?? null,
      meta.cameraModel ?? null,
      nowIso(),
      isoIn(TTL_MS),
    );

  return token;
}

/**
 * Look up a pending upload for a user, without consuming it.
 *
 * Returns null for a token that is unknown, expired, or owned by someone else.
 * All three are reported identically because they are the same answer from the
 * caller's point of view: there is no photo here for you.
 *
 * @param {unknown} token
 * @param {number} userId
 */
export function getPendingPhoto(token, userId) {
  if (typeof token !== 'string' || !token || token.length > 200) return null;
  const row = db()
    .prepare('SELECT * FROM pending_photos WHERE token = ? AND user_id = ?')
    .get(token, userId);
  if (!row) return null;
  if (Date.parse(row.expires_at) <= Date.now()) return null;
  return row;
}

/**
 * Shape a pending row into the argument addPhoto expects.
 * @param {any} row
 */
export function pendingToPhotoInput(row) {
  return {
    storageName: row.storage_name,
    mimeType: row.mime_type,
    byteSize: row.byte_size,
    sha256: row.sha256,
    originalName: row.original_name,
    metadata: {
      gpsLatitude: row.gps_latitude,
      gpsLongitude: row.gps_longitude,
      gpsAltitudeMetres: row.gps_altitude_m,
      hadGps: row.had_gps === 1,
      capturedAt: row.captured_at,
      capturedAtRaw: row.captured_at_raw,
      cameraMake: row.camera_make,
      cameraModel: row.camera_model,
    },
  };
}

/**
 * Drop the pending record once its file has been attached to a survey.
 *
 * Deletes only the row. The file stays, because at this point the photos table
 * owns it.
 *
 * @param {string} token
 */
export function consumePendingPhoto(token) {
  db().prepare('DELETE FROM pending_photos WHERE token = ?').run(token);
}

/**
 * Discard a pending upload and delete its file.
 *
 * Used when the user replaces it with a different photo before resubmitting.
 *
 * @param {any} row
 * @param {string} uploadDir
 */
export function discardPendingPhoto(row, uploadDir) {
  if (!row) return;
  db().prepare('DELETE FROM pending_photos WHERE id = ?').run(row.id);
  removeUpload(uploadDir, row.storage_name);
}

/**
 * Delete a stored upload from disk, safely.
 *
 * The name was generated by us, but it is resolved and checked for containment
 * anyway: this function deletes files, and a path-traversal bug here would be
 * considerably worse than the duplicated check is expensive.
 *
 * @param {string} uploadDir
 * @param {string} storageName
 */
export function removeUpload(uploadDir, storageName) {
  if (typeof storageName !== 'string' || !storageName) return;
  const full = path.join(uploadDir, storageName);
  const root = path.resolve(uploadDir) + path.sep;
  if (!path.resolve(full).startsWith(root)) return;
  try {
    fs.unlinkSync(full);
  } catch {
    // Already gone is the desired end state.
  }
}

/**
 * Delete expired pending uploads and their files.
 *
 * Without this the table and the disk both grow forever, which is the quieter
 * half of the bug this module exists to fix.
 *
 * @param {string} uploadDir
 * @returns {number} how many were removed
 */
export function prunePendingPhotos(uploadDir) {
  const expired = db()
    .prepare('SELECT id, storage_name FROM pending_photos WHERE expires_at <= ?')
    .all(nowIso());
  for (const row of expired) {
    removeUpload(uploadDir, row.storage_name);
  }
  if (expired.length > 0) {
    db()
      .prepare('DELETE FROM pending_photos WHERE expires_at <= ?')
      .run(nowIso());
  }
  return expired.length;
}

/**
 * Find upload files that no table references, and optionally delete them.
 *
 * A safety net rather than a normal code path. Files can be orphaned by a crash
 * between writing the file and writing its row, and before pending_photos
 * existed every failed submit orphaned one. Reporting is the default; deleting
 * requires asking.
 *
 * @param {string} uploadDir
 * @param {{delete?: boolean}} [options]
 * @returns {{orphans: string[], bytes: number, deleted: number}}
 */
export function findOrphanedUploads(uploadDir, options = {}) {
  /** @type {string[]} */
  let names = [];
  try {
    names = fs.readdirSync(uploadDir);
  } catch {
    return { orphans: [], bytes: 0, deleted: 0 };
  }

  const referenced = new Set([
    ...db().prepare('SELECT storage_name FROM photos').all().map((r) => r.storage_name),
    ...db()
      .prepare('SELECT storage_name FROM pending_photos')
      .all()
      .map((r) => r.storage_name),
  ]);

  const orphans = [];
  let bytes = 0;
  let deleted = 0;

  for (const name of names) {
    if (referenced.has(name)) continue;
    const full = path.join(uploadDir, name);
    let size = 0;
    try {
      const stat = fs.statSync(full);
      if (!stat.isFile()) continue;
      size = stat.size;
    } catch {
      continue;
    }
    orphans.push(name);
    bytes += size;
    if (options.delete) {
      removeUpload(uploadDir, name);
      deleted += 1;
    }
  }

  return { orphans, bytes, deleted };
}
